version: '3.9'
services:
  miapp:
    build: .
    ports:
      - "8000:8000"
    links:
      - falabella
  falabella:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Delfin173